### ISSUE TITLE
vue_find_resource() got an unexpected keyword argument 'cdn'

### ISSUE THREAD

**Issue by askz** [taogeT/flask-vue#1]
Hi, 

First thanks for your time, I've been looking for vuejs integrations to flask but most are 3 years old ahah.

Could you please tell me if I have something more to do after I init_app(app) ? 
I tried to extends vue/base.html then 

```
{% block scripts %}
{{ super() }}
{% endblock %}
```
And I got `vue_find_resource() got an unexpected keyword argument 'cdn'`

**Comment by taogeT** [comment]
Hi @askz ,

Thanks for using my integration. I fixed vue/base.html bug (function vue_find_resource argument has changed after ver 0.3). 

My plan is to write vue/base.html as flask-bootstrap base.html. For now, the integration is still BETA.

**Comment by askz** [comment]
Thanks ! Will give it a try !
