### ISSUE TITLE
Do you have some example of implementation?

### ISSUE THREAD

**Issue by askz** [taogeT/flask-vue#2]
Hi again, 

I'm stuck with the integration when I need to run flask and webpack etc.
Can't see were to start.. 
I saw in your livetv mining project that you got separate frontend/backend, is it easier?

**Comment by taogeT** [comment]
Hi @askz,

Sorry for replying you so late. (I‘m on vacation)

In my opinion, both ways (split frontend/server or not) have specific difficulties. The case you choose  depends on the product environment. For my project livetv_mining, it deploys on AWS Free Tier server and free server performance is poor. So I had to use split case(and other subplan) to save CPU work time.
In real life, many internet companies choose the popular solution: RESTAPI ＋ iOS ＋ Android ＋ Web and more traditional companies choose integration all on server. 

So my suggestion is that: If you are a beginner about Flask, you can start from tutorial: [flasky](https://github.com/miguelgrinberg/flasky) ([py3 version](https://github.com/taogeT/flask_web_development_python3)). If you have use experience about Flask, you can learn how to split frontend/server immediately. The examples I refer to are [vue-hackernews-2.0 webpack2.0](https://github.com/vuejs/vue-hackernews-2.0), [vuejs-templates webpack1.0](https://github.com/vuejs-templates/webpack) and webpack official document.

Would it help you to smooth learning curve ?

**Comment by askz** [comment]
Thank you. 
I was really wondering why you did that package (flask-vue) and on the other having a vue project with splitted front/back.

I will definitely check the split solution !

Cheers!

**Comment by taogeT** [comment]
@askz

Simple put, I had a flask/vue project which should be deployed inner & outer net in the meantime.

When you visit website in outer net, the best way to save net flow is using CDN for scripts resource. When you visit website in inner net, the visitor can not get resource stored outer network. At the same time, the developers need to deploy project easy and configurable.

So I package the flask-vue and it can config project to use CDN or Local files.
