### ISSUE TITLE
What is Flask-Vue good for?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [taogeT/flask-vue#3]
Sorry for that type of question, but I am kind of a noob in web development and still learning Python and just played around a bit with Flask.

I am looking forward to develop a web application in Flask which I would like to have same fancy GUI as if it was made with Vue, AngularJS, ReactJS or other JavaScript Framework. But I hope that I can avoid having to mess with JavaScript at all. So, is Flask-Vue here to my rescue or am I totally mistaken about it's sense?

Cheers Tset

**Comment by taogeT** [comment]
Hi @Tset-Noitamotua ,

Simple put, The integration Flask-Vue helps me to deploy project on limited network environment easy and configurable. I think you mistaken it.

As you are a beginner, I advise you to start from tutorial: [flasky](https://github.com/miguelgrinberg/flasky) ([py3 version](https://github.com/taogeT/flask_web_development_python3)). After that, you would try to replace Flask template Jinjia2 with Vue+Webpack (smooth learning curve, as [my project](https://github.com/taogeT/livetv_mining)).

**Comment by Tset-Noitamotua** [comment]
Thank you for clarification. I am aware of flasky (it's on my todo list) but didn't know that it was not Python3 ready - good to know, will check out your fork.

I think it's worth to mention what your Flask-Vue is good for in README, it surely will help others, too. Btw. how many visitors does this repo has (if that's not a secret)? (you can look that up in Graphs --> Traffic --> Visitors)

**Comment by taogeT** [comment]
@Tset-Noitamotua 

OK, I will add it in README. The Flask-Vue only has 75 unique visitors so far.

**Comment by Mark24Code** [comment]
这应该就是简单地引入了vue的js吧。
vue的威力要配合webpack，和后端独立开来。前后端分离式开发。

如果楼主能把webpack和vue的工作链整合在一块，塞进Flask，那就神作了。
Flask MVC Full Stack+Flask SPA Full Stack。

**Comment by taogeT** [comment]
@Mark24Code 

目前通过我自己的实践看来，更建议将vue+webpack和FLASK独立开。前后端分离的本意也是如此，互相独立，仅由RESTAPI通信。

**Comment by Tset-Noitamotua** [comment]
Is it 中国? 

我明白只有站  :-(

;-)

**Comment by taogeT** [comment]
@Tset-Noitamotua Both of us are from China.

**Comment by Tset-Noitamotua** [comment]
Cool. A friend of mine lives in 上海. But I have never been in China ... yet. May be I visit him one day.

:hand: from :de:
